version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: stock-dashboard-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockmarket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-dashboard-backend
    depends_on:
      - postgres
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/stockmarket
      - NODE_ENV=production
    ports:
      - "5000:5000"
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-dashboard-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data:
